repos:
  - repo: "https://github.com/codespell-project/codespell"
    rev: "v2.4.1"
    hooks:
      - id: "codespell"
        args: ["--config=.codespellrc"]
  - repo: "https://github.com/pre-commit/mirrors-clang-format"
    rev: "v21.1.6"
    hooks:
      - id: "clang-format"
        types_or: []
        files: '\.c\.in$|\.h\.in$|\.c$|\.h$'
        args: ["--style=file"]
        exclude: |
            (?x)^(
                  crypto/objects/obj_dat.h|
                  crypto/objects/obj_xref.h|
                  include/openssl/obj_mac.h
                 )$
