language: c

addons:
    apt:
        packages:
            - clang-3.6
            - gcc-5
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test

os:
    - linux
    - osx

compiler:
    - clang
    - clang-3.6
    - gcc
    - gcc-5

env:
    - CONFIG_OPTS=""
    - CONFIG_OPTS="shared"
    - CONFIG_OPTS="no-pic"
    - CONFIG_OPTS="--debug --strict-warnings enable-crypto-mdebug enable-rc5 enable-md2"
    - CONFIG_OPTS="--unified" BUILDONLY="yes"
    - CONFIG_OPTS="--unified shared" BUILDONLY="yes"
    - CONFIG_OPTS="--unified --debug --strict-warnings enable-rc5 enable-md2" BUILDONLY="yes"

matrix:
    include:
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="-fsanitize=address"
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="no-asm --strict-warnings -fno-sanitize-recover -fsanitize=address -fsanitize=undefined enable-rc5 enable-md2"
        - os: linux
          compiler: gcc-5
          env: CONFIG_OPTS="-fsanitize=address"
        - os: linux
          compiler: gcc-5
          env: CONFIG_OPTS="no-asm --strict-warnings -fno-sanitize-recover -fsanitize=address -fsanitize=undefined enable-rc5 enable-md2"
        - os: linux
          compiler: clang
          env: CONFIG_OPTS="no-engine" BUILDONLY="yes"
    exclude:
        - os: osx
          compiler: clang-3.6
        - os: osx
          compiler: gcc
        - os: osx
          compiler: gcc-5

before_script:
    - sh .travis-create-release.sh $TRAVIS_OS_NAME
    - tar -xvzf _srcdist.tar.gz
    - cd _srcdist
    - if [ "$CC" == i686-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw $CONFIG_OPTS -Wno-pedantic-ms-format;
      elif [ "$CC" == x86_64-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw64 $CONFIG_OPTS -Wno-pedantic-ms-format;
      else
          ./config $CONFIG_OPTS;
      fi
    - cd ..

script:
    - cd _srcdist
    - make
    - if [ -z "$BUILDONLY" ]; then
          HARNESS_VERBOSE=yes make test
      fi
    - cd ..

notifications:
    email:
        - openssl-commits@openssl.org

