language: c

addons:
    apt:
        packages:
            - clang-3.6
            - gcc-5
            - binutils-mingw-w64
            - gcc-mingw-w64
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test

os:
    - linux
    - osx

compiler:
    - clang
    - clang-3.6
    - gcc
    - gcc-5
    - i686-w64-mingw32-gcc
    - x86_64-w64-mingw32-gcc

env:
    - CONFIG_OPTS=""
    - CONFIG_OPTS="shared"
    - CONFIG_OPTS="--debug --strict-warnings"

matrix:
    include:
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="--debug --strict-warnings -fsanitize=address"
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="--debug --strict-warnings -fPIE -pie -fsanitize=memory"
        - os: linux
          compiler: gcc-5
          env: CONFIG_OPTS="--debug --strict-warnings -fsanitize=address"
    exclude:
        - os: osx
          compiler: clang-3.6
        - os: osx
          compiler: gcc-5
        - os: osx
          compiler: i686-w64-mingw32-gcc
        - os: osx
          compiler: x86_64-w64-mingw32-gcc
    allow_failures:
        - compiler: i686-w64-mingw32-gcc
          env: CONFIG_OPTS="--debug --strict-warnings"
        - compiler: x86_64-w64-mingw32-gcc
          env: CONFIG_OPTS="--debug --strict-warnings"

before_script:
    - if [ "$CC" == i686-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw $CONFIG_OPTS;
      elif [ "$CC" == x86_64-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw64 $CONFIG_OPTS;
      else
          ./config $CONFIG_OPTS;
      fi

script:
    - make
    - if [ -z "$CROSS_COMPILE" ]; then HARNESS_VERBOSE=yes make test; fi

notifications:
    email:
        - openssl-commits@openssl.org
