version: 2

# TODO: Add psutil to CI images.

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Clone liboqs
        command: ./oqs-scripts/clone_liboqs.sh # unconditional checkout to test for changes there
    - run:
        name: Build liboqs
        command: .circleci/git_no_checkin_in_last_day.sh || ./oqs-scripts/build_liboqs.sh
    - run:
        name: Build OpenSSL
        command: .circleci/git_no_checkin_in_last_day.sh || ./oqs-scripts/build_openssl.sh
    - run:
        name: Run OpenSSL tests
        command: .circleci/git_no_checkin_in_last_day.sh || (env LD_LIBRARY_PATH="$(pwd):$(pwd)/oqs/lib" make test)
    - run:
        name: Run OQS connection, CMS and speed tests
        # TODO: Add psutil to CI images.
        command: .circleci/git_no_checkin_in_last_day.sh || (apt install python3-psutil && env LD_LIBRARY_PATH="$(pwd):$(pwd)/oqs/lib" python3 -m pytest --numprocesses=auto oqs-test/test_tls_full.py oqs-test/test_cms.py oqs-test/test_speed.py --junitxml=oqs-test/tmp/test-results/pytest/test-results.xml)
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs-test/tmp/test-results

.macopenssl_job: &macopenssljob
    macos:
       xcode: "11.3.0"
    steps:
        - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
        - run:
            name: Install dependencies
            command: |
              .circleci/git_no_checkin_in_last_day.sh || (
              brew unlink python@2 &&
              brew install cmake ninja &&
              pip3 install --user pytest pytest-xdist psutil
              )
        - run:
            name: Clone liboqs
            command: ./oqs-scripts/clone_liboqs.sh # unconditional checkout to test for changes there
        - run:
            name: Build liboqs
            command: .circleci/git_no_checkin_in_last_day.sh || ./oqs-scripts/build_liboqs.sh
        - run:
            name: Build OpenSSL
            command: .circleci/git_no_checkin_in_last_day.sh || (./Configure ${OPENSSL_LIBTYPE} darwin64-x86_64-cc no-tests && make -j3)
        - run:
            name: Run OQS connection, CMS and speed tests
            command: .circleci/git_no_checkin_in_last_day.sh || (env DYLD_LIBRARY_PATH="$(pwd):$(pwd)/oqs/lib" python3 -m pytest --numprocesses=auto oqs-test/test_tls_full.py oqs-test/test_cms.py oqs-test/test_speed.py --junitxml=oqs-test/tmp/test-results/pytest/test-results.xml)
        - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
            path: oqs-test/tmp/test-results

.boringssl_interop_job: &boringsslinteropjob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Clone liboqs and BoringSSL
        command: ./oqs-scripts/clone_liboqs.sh && ./oqs-scripts/clone_boringssl.sh
    - run:
        name: Build liboqs
        command: .circleci/git_no_checkin_in_last_day.sh || ./oqs-scripts/build_liboqs.sh
    - run:
        name: Build BoringSSL
        command: .circleci/git_no_checkin_in_last_day.sh || ./oqs-scripts/build_boringssl.sh
    - run:
        name: Build OpenSSL
        command: .circleci/git_no_checkin_in_last_day.sh || (./Configure linux-x86_64 no-shared no-tests && make -j15)
    - run:
        name: Test BoringSSL client against OpenSSL server
        command: .circleci/git_no_checkin_in_last_day.sh || (python3 -m pytest --numprocesses=auto oqs-interop-test/test_full.py --client-prog=boringssl/build/ssl/test/bssl_shim --client-type=bssl --server-prog=apps/openssl --server-type=ossl --junitxml=oqs-interop-test/tmp/test-results/pytest/bssl_client-test-results.xml)
    - run:
        name: Test OpenSSL client against BoringSSL server
        command: .circleci/git_no_checkin_in_last_day.sh || (python3 -m pytest --numprocesses=auto oqs-interop-test/test_full.py --client-prog=apps/openssl --client-type=ossl --server-prog=boringssl/build/tool/bssl --server-type=bssl --junitxml=oqs-interop-test/tmp/test-results/pytest/ossl_client-test-results.xml)
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs-interop-test/tmp/test-results

jobs:
  debian_buster-shared_oqs-static_ossl:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      LIBOQS_LIBTYPE: shared
  ubuntu_bionic-shared_oqs-shared_ossl:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      LIBOQS_LIBTYPE: shared
      OPENSSL_LIBTYPE: shared
  ubuntu_bionic-static_oqs-static_ossl:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
  ubuntu_bionic-static_oqs-static_ossl-boringssl-interop:
    <<: *boringsslinteropjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      LIBOQS_USE_OPENSSL: OFF
  macOS-shared_oqs-shared_ossl:
    <<: *macopenssljob
    environment:
      LIBOQS_LIBTYPE: shared
      OPENSSL_LIBTYPE: shared
  macOS-static_oqs-static_ossl:
    <<: *macopenssljob

workflows:
  version: 2
  build:
    jobs:
      - ubuntu_bionic-static_oqs-static_ossl
      - ubuntu_bionic-shared_oqs-shared_ossl
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - OQS-OpenSSL_1_1_1-stable
    jobs:
      - debian_buster-shared_oqs-static_ossl
      - macOS-shared_oqs-shared_ossl
      - macOS-static_oqs-static_ossl
      - ubuntu_bionic-shared_oqs-shared_ossl
      - ubuntu_bionic-static_oqs-static_ossl-boringssl-interop
