jobs:
  build:
    docker:
      - image: cimg/base:2021.12
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update && sudo apt-get install -y cowsay
      - run: cowsay Continuous Integration Rocks!