name: Build

on:
  push:
    branches: [ "master" ]
  pull_request_target:
    types:
      - closed

jobs:
  build32:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install mingw-w64 mingw-w64-tools
    - name: make build directory
      run: mkdir build
    - name: Configure
      run: ./Configure --cross-compile-prefix=/usr/bin/i686-w64-mingw32- mingw --prefix=$(pwd)/build --openssldir=$(pwd)/build
    - name: make
      run: make
    - name: make install
      run: make install_sw
    - name: upload build
      uses: actions/upload-artifact@v3
      with:
        name: build32
        path: build
  build64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install mingw-w64 mingw-w64-tools
    - name: make build directory
      run: mkdir build
    - name: Configure
      run: ./Configure --cross-compile-prefix=/usr/bin/x86_64-w64-mingw32- mingw64 --prefix=$(pwd)/build --openssldir=$(pwd)/build
    - name: make
      run: make
    - name: make install
      run: make install_sw
    - name: upload build
      uses: actions/upload-artifact@v3
      with:
        name: build64
        path: build
  release:
    permissions:
      contents: write
    needs: [build32, build64]
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: zip artifacts
      run: |
        zip -r openssl-win32-dev.zip build32/*
        zip -r openssl-win64-dev.zip build64/*
        zip -r -j openssl-win32.zip build32/bin
        zip -r -j openssl-win64.zip build64/bin
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        files: |
          openssl-win32-dev.zip
          openssl-win64-dev.zip
          openssl-win32.zip
          openssl-win64.zip
