# Copyright 2022 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Windows Compression GitHub CI

on:
  pull_request:
    paths:
      - 'crypto/comp/*.c'
  push:
    paths:
      - '**.c'

permissions:
  contents: read

jobs:
  zstd:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: checkout fuzz/corpora submodule
      run: git submodule update --init --depth 1 fuzz/corpora
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ilammy/setup-nasm@v1
    - name: prepare the build directory
      run: mkdir _build
    - name: Get zstd
      working-directory: _build
      run: |
        vcpkg install zstd:x64-windows
    - name: config
      working-directory: _build
      run: |
        perl ..\Configure enable-comp enable-zstd --with-zstd-include=C:\vcpkg\packages\zstd_x64-windows\include --with-zstd-lib=C:\vcpkg\packages\zstd_x64-windows\lib\zstd.lib no-makedepend VC-WIN64A
        perl configdata.pm --dump
    - name: build
      working-directory: _build
      run: nmake
    - name: test
      working-directory: _build
      run: |
        $env:Path+=";C:\vcpkg\packages\zstd_x64-windows\bin"
        nmake test VERBOSE_FAILURE=yes TESTS="-test_fuzz* -test_fipsload" HARNESS_JOBS=4
  brotli:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: checkout fuzz/corpora submodule
      run: git submodule update --init --depth 1 fuzz/corpora
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ilammy/setup-nasm@v1
    - name: prepare the build directory
      run: mkdir _build
    - name: Get brotli
      working-directory: _build
      run: |
        vcpkg install brotli:x64-windows
    - name: config
      working-directory: _build
      run: |
        perl ..\Configure enable-comp enable-brotli --with-brotli-include=C:\vcpkg\packages\brotli_x64-windows\include --with-brotli-lib=C:\vcpkg\packages\brotli_x64-windows\lib no-makedepend VC-WIN64A
        perl configdata.pm --dump
    - name: build
      working-directory: _build
      run: nmake
    - name: test
      working-directory: _build
      run: |
        $env:Path+=";C:\vcpkg\packages\brotli_x64-windows\bin"
        nmake test VERBOSE_FAILURE=yes TESTS="-test_fuzz* -test_fipsload" HARNESS_JOBS=4
